#Development YAML file for Transcendance

services:
  #ADMINER
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - t42bcnet
    depends_on:
      postgresql:
        condition: service_healthy
  
  #FRONTEND
  frontend:
    build: 
      target: development
    environment:
      - VITE_API_URL=http://backend:${BACKEND_PORT}
      - VITE_APP_ENV=development
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  
  #BACKEND
  backend:
    build: 
      target: development
      args:
        - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresql:5432/${DB_NAME}?schema=prisma
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresql:5432/${DB_NAME}?schema=prisma
      - GIT_BRANCH=${GIT_BRANCH}
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - BASE_URL=${CLIENT_URL}
      - LOG_LEVEL=debug
      - NODE_ENV=development
      - PRISMA_QUERY_LOGGING=true
      - PRISMA_METRICS=true
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
