#YAML file for Transcendance

networks:
  t42bcnet:
    name: t42bcnet
    driver: bridge

volumes:
  db_data:
  frontend_data:
  prisma_migrations:

services:
  #NGINX PROXY
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - t42bcnet
    volumes:
      - ./requirements/nginx/templates/:/etc/nginx/templates
      - frontend_data:/var/www/:ro 
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${FRONTEND_PORT}
    ports:
      - ${EXPOSED_PORT}:${FRONTEND_PORT}
    restart: unless-stopped

  #POSTGRESQL
  postgresql:
    container_name: postgresql
    image: postgres:17.7-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./requirements/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - t42bcnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  #FRONTEND
  frontend:
    container_name: frontend
    build: 
      context: ../
      dockerfile: docker/requirements/frontend/dockerfile
      target: development
      args:
        - NODE_VERSION=lts-alpine
    working_dir: /app
    #environment:
    #  - NODE_ENV=production
      #- VITE_API_URL=http://backend:${BACKEND_PORT}
    volumes:
      - frontend_data:/app/dist
    ports:
      - "5173:5173"
    networks:
      - t42bcnet
    restart: unless-stopped
  
  #BACKEND
  backend:
    container_name: backend
    build: 
      context: ../
      dockerfile: docker/requirements/backend/dockerfile
      target: development
      args:
        - NODE_VERSION=lts-alpine
        - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresql:${DB_PORT}/${DB_NAME}?schema=prisma&connection_limit=5
    working_dir: /app
    volumes:
      - prisma_migrations:/app/prisma/migrations
      - ../server/prisma/migrations:/migrations
    environment:
    #  - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresql:${DB_PORT}/${DB_NAME}?schema=prisma&connection_limit=5
      - GIT_BRANCH=${GIT_BRANCH}
    ports:
      - "3001:3001"
    networks:
      - t42bcnet
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
