#YAML file for Transcendance

networks:
  t42bcnet:
    name: t42bcnet
    driver: bridge

volumes:
  db_data:
  frontend_data:

services:

  #NGINX PROXY
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - t42bcnet
    volumes:
      - ./requirements/nginx/templates/:/etc/nginx/templates
      - frontend_data:/var/www/:ro 
    environment:
      - NGINX_HOST=${FRONTEND_HOST}
      - NGINX_PORT=${FRONTEND_PORT}
    ports:
      - ${DOCKER_PORT}:${FRONTEND_PORT}
    restart: unless-stopped

  #POSTGRESQL
  postgresql:
    container_name: postgresql
    image: postgres:17.7-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - t42bcnet
    restart: unless-stopped
  
  #FRONTEND
  frontend:
    container_name: frontend
    build: 
      context: ../
      dockerfile: docker/requirements/frontend/dockerfile 
    working_dir: /app
    image: frontend:react
    volumes:
      - ../client:/src:ro
      - frontend_data:/app/dist 
    networks:
      - t42bcnet
    restart: unless-stopped
